import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { Inter } from "next/font/google";

import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });
import NextNProgress from "nextjs-progressbar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NProgress from "nprogress";

export default function App({ Component, pageProps }: AppProps) {
  NProgress.configure({ showSpinner: false });
  return (
    <>
      <Head>
        <title>Sableng Movie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextNProgress color="#E11D48" />
      <Navbar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}
